/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '11/21/20, 12:19 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-754.6.3.el6.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:81.0) Gecko/20100101 Firefox/81.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/38/main?locale=en_US&zone=GMT-07%253A00' 
 *
 */

options validvarname=any;
ods noproctitle;
ods graphics / imagemap=on;

/* Scatter plot matrix macro */
%macro scatterPlotMatrix(xVars=, title=, groupVar=);
	proc sgscatter data=MIS543.M4_PRODUCTSALESADVERTISING;
		matrix &xVars / %if(&groupVar ne %str()) %then
			%do;
				group=&groupVar legend=(sortorder=ascending) %end;
		diagonal=(histogram normal);
		title &title;
	run;

	title;
%mend scatterPlotMatrix;

/* Regression scatter plot macro */
%macro regressionScatterplot(xVar=, yVar=, title=, groupVar=);
	proc sgscatter data=MIS543.M4_PRODUCTSALESADVERTISING;
		plot (&yVar)*(&xVar) / %if(&groupVar ne %str()) %then
			%do;
				group=&groupVar legend=(sortorder=ascending) %end;
		reg;
		title &title;
	run;

	title;
%mend regressionScatterplot;

/* Histogram and box plot template */
proc template;
	define statgraph histobox;
		dynamic AVAR;
		begingraph;
		entrytitle "Distribution of " eval(catq('q', colname(AVAR)));
		layout lattice / rows=2 columndatarange=union rowgutter=0 rowweights=(0.75 
			0.25);
		layout overlay / yaxisopts=(offsetmax=0.1) xaxisopts=(display=none);
		layout gridded / columns=2 border=on autoalign=(topright topleft);
		endlayout;
		histogram AVAR /;
		endlayout;
		layout overlay /;
		BoxPlot Y=AVAR / orient=horizontal;
		endlayout;
		endlayout;
		endgraph;
	end;
run;

%scatterPlotMatrix(xVars=sales radio paper TV POS, title="Scatter plot matrix", 
	groupVar=);
%regressionScatterplot(xVar=radio, yVar=sales, title="sales vs radio");
%regressionScatterplot(xVar=paper, yVar=sales, title="sales vs paper");
%regressionScatterplot(xVar=TV, yVar=sales, title="sales vs TV");
%regressionScatterplot(xVar=POS, yVar=sales, title="sales vs POS");

proc sgrender data=MIS543.M4_PRODUCTSALESADVERTISING template=histobox;
	dynamic AVAR='sales';
run;

proc sgrender data=MIS543.M4_PRODUCTSALESADVERTISING template=histobox;
	dynamic AVAR='radio';
run;

proc sgrender data=MIS543.M4_PRODUCTSALESADVERTISING template=histobox;
	dynamic AVAR='paper';
run;

proc sgrender data=MIS543.M4_PRODUCTSALESADVERTISING template=histobox;
	dynamic AVAR='TV';
run;

proc sgrender data=MIS543.M4_PRODUCTSALESADVERTISING template=histobox;
	dynamic AVAR='POS';
run;