/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '11/21/20, 12:31 PM' 
 * Generated by 'sasdemo' 
 * Generated on server 'LOCALHOST' 
 * Generated on SAS platform 'Linux LIN X64 2.6.32-754.6.3.el6.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:81.0) Gecko/20100101 Firefox/81.0' 
 * Generated on web client 'http://localhost:10080/SASStudio/38/main?locale=en_US&zone=GMT-07%253A00' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc glmselect data=MIS543.M4_PRODUCTSALESADVERTISING 
		outdesign(addinputvars)=Work.reg_design plots=(criterionpanel);
	model sales=radio TV / showpvalues selection=backward
    
   (select=sbc);
run;

proc reg data=Work.reg_design alpha=0.05 plots(only)=(diagnostics residuals 
		observedbypredicted);
	ods select DiagnosticsPanel ResidualPlot ObservedByPredicted;
	model sales=&_GLSMOD /;
	run;
quit;

proc delete data=Work.reg_design;
run;